spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${keycloak.port}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  rabbitmq:
    host: localhost
    username: rmuser
    password: rmpassword

rabbitmq:
  queue: messageQueue
  exchange: messageExchange
  routingKey: messageRoutingKey

keycloak:
  port: 8282
  realm: hrm-realm
  client-id: spring-boot-rest-api
  id-client: c1807ac7-3c02-4f89-b85e-6aed36598337
  token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  realm-uri: http://localhost:${keycloak.port}/admin/realms/${keycloak.realm}
